trigger:
  - main

# Nightly regression schedule (2 AM NZ time)
schedules:
- cron: "0 14 * * *"   # 14:00 UTC = 02:00 NZST
  displayName: Nightly Regression
  branches:
    include:
      - main
  always: true

parameters:
- name: testType
  displayName: Select test type
  type: string
  default: regression
  values:
    - smoke
    - regression
    - shopping
    - contact
    - all

pool:
  vmImage: 'ubuntu-latest'

variables:
  BASE_URL: 'http://jupiter.cloud.planittesting.com'

jobs:
- job: PlaywrightTests
  displayName: "Run Tests on "
  strategy:
    matrix:
      chrome:
        browser: Chrome
      edge:
        browser: Edge

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: node -v
      displayName: 'Check Node version'

    - script: npm ci
      displayName: 'Install dependencies'

    - script: npx tsc --noEmit
      displayName: 'Validate TypeScript'

    - script: npx playwright install --with-deps
      displayName: 'Install Playwright browsers'

    # Run tests based on dropdown selection
    - script: |
        if [ "${{ parameters.testType }}" = "smoke" ]; then
          npx playwright test --grep @smoke --project=$(browser)
        elif [ "${{ parameters.testType }}" = "regression" ]; then
          npx playwright test --grep @regression --project=$(browser)
        else
          npx playwright test --project=$(browser)
        fi
      displayName: "Run Playwright tests"
      env:
        BASE_URL: $(BASE_URL)

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-results/results.xml'
        testRunTitle: 'Playwright $(browser) tests'
        failTaskOnFailedTests: true
      displayName: 'Publish JUnit test results'

    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        pathToPublish: 'playwright-report'
        artifactName: 'playwright-report-$(browser)'
      displayName: 'Publish Playwright HTML report'

    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        pathToPublish: 'test-results'
        artifactName: 'test-results-$(browser)'
      displayName: 'Publish test results'
